// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.lisaacademy.robotics.theTerminator.commands;
import InsightLT.DecimalData;
import InsightLT.InsightLT;
import edu.wpi.first.wpilibj.command.Command;
import org.lisaacademy.robotics.theTerminator.Robot;
/**
 *
 */
import edu.wpi.first.wpilibj.DriverStation;
public class  LCDStatus extends Command {
    
    DecimalData battery;
    
    public LCDStatus() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lCD);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.lCD.display = new InsightLT(InsightLT.FOUR_ZONES);
        battery = new DecimalData("Batt:");
        Robot.lCD.display.registerData(battery, 1);
        
        Robot.lCD.display.startDisplay();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        battery.setData(DriverStation.getInstance().getBatteryVoltage());
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
